title: Site

pages: false
  sort: Permet_de_cacher_les_sous_pages

files: true

fields:
  title:
    label: Title
    type:  markdown
    width: 1/3
    
  logo:
    label: Site Logo
    type: select
    options: images
    width: 1/3

  author:
    label: Author
    type:  text
    icon: user
    width: 1/3
    
  description:
    label: Description
    type:  markdown  

 
  contactinfos:
    label: Contact Informations
    type:  headline    
    
  email:
    label: Email
    type: email
  website:
    label: Website
    type: url
    width: 1/2
  twitter:
    label: Twitter
    type: text
    placeholder: @
    icon: twitter
    width: 1/2
    
  copyright:
    label: Copyright
    type:  markdown
